output   = "db/models"
wipe     = true
no-tests = true

[psql]
  dbname = "newdatabase"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  blacklist = ["schema_migrations"]
